# DUBLIN BIKES PROJECT

    Number of Stations in Dublin: 101
    
    Bike Station capacity = "bikes" + "free"  
        bikes           1276     Bikes available for hire on 3/7/16 at 11:17am
        free            1877     Bike spots available to park on 3/7/16 at 11:17
        TOTAL BIKE = Sum() = 3153

    "number" -> ID for the station

In [22]:
import pandas as pd
from pandas import Series, DataFrame
import numpy as np
import json
import requests
from time import sleep, strftime, gmtime


url = 'http://api.citybik.es/dublinbikes.json'
json_data = requests.get(url).text

print (json_data[:500])

[
  {
    "bikes": 33,
    "name": "FENIAN STREET",
    "idx": 0,
    "lat": 53341428,
    "timestamp": "2016-03-07T13:32:43.746Z",
    "lng": -6246720,
    "id": 0,
    "free": 0,
    "number": 63
  },
  {
    "bikes": 15,
    "name": "CITY QUAY",
    "idx": 1,
    "lat": 53346637,
    "timestamp": "2016-03-07T13:32:43.779Z",
    "lng": -6246154,
    "id": 1,
    "free": 15,
    "number": 99
  },
  {
    "bikes": 23,
    "name": "FITZWILLIAM SQUARE EAST",
    "idx": 2,

In [23]:
#Parse results based on "bikes" as index 0
json_series = Series(json_data)
# test

print (json_series)

0    [\n  {\n    "bikes": 33, \n    "name": "FENIAN...
dtype: object

In [24]:
#Other attempt with clipboard (all json data 12.27pm 03/04/16) #Only working if copy data from website
import numpy as np
import pandas as pd
#from pandas import Series, DataFrame
import webbrowser
website = 'http://api.citybik.es/dublinbikes.json'
#webbrowser.open(website)

bike_frame = pd.read_clipboard()
print(bike_frame[:200])

Empty DataFrame
Columns: [1c8d24323042b11c89877648adfe3c180f15fa3c]
Index: []

In [25]:
import numpy as np
import pandas as pd
from pandas import Series, DataFrame
import webbrowser
website = 'http://api.citybik.es/dublinbikes.json'
#webbrowser.open(website)

bike_frame = pd.read_json(website)
print(bike_frame[:500])

print(len(bike_frame.index))

     bikes  free   id  idx       lat      lng  \
0       33     0    0    0  53341428 -6246720
1       15    15    1    1  53346637 -6246154
2       23    16    2    2  53335211 -6250900
3        1    29    3    3  53339005 -6300217
4       10    30    4    4  53340714 -6308191
5        1    34    5    5  53338776 -6303950
6        2    28    6    6  53350291 -6273507
7       12     8    7    7  53346874 -6272976
8        0    40    8    8  53354929 -6269425
9       10    30    9    9  53330662 -6260177
10       1    37   10   10  53347972 -6291804
11       4    25   11   11  53343565 -6275071
12      12    13   12   12  53347106 -6292041
13       4    26   13   13  53330362 -6265163
14       0    27   14   14  53358115 -6265601
15      30     0   15   15  53339434 -6246548
16       6    24   16   16  53347692 -6278214
17       3    27   17   17  53330091 -6268044
18      20     9   18   18  53347884 -6248048
19      18     2   19   19  53339764 -6251988
20       1    24   20   20  53357043 -6263232
21      38     2   21   21  53337824 -6256035
22      14     6   22   22  53341288 -6258117
23       0    30   23   23  53358437 -6260641
24       0    30   24   24  53356299 -6258586
25      20    20   25   25  53346026 -6243576
26      23     1   26   26  53343034 -6263578
27       9    20   27   27  53346057 -6268001
28       0    40   28   28  53347122 -6234749
29      15     1   29   29  53344007 -6266802
..     ...   ...  ...  ...       ...      ...
71       2    38   71   71  53347440 -6238523
72      17     6   72   72  53349013 -6260311
73      10    19   73   73  53348875 -6267459
74       0    30   74   74  53343893 -6280531
75      38     2   75   75  53341655 -6236198
76      24     5   76   76  53334432 -6245575
77      30     9   77   77  53342638 -6238695
78       0    20   78   78  53355610 -6261397
79       0    30   79   79  53342081 -6275233
80       2    28   80   80  53359624 -6260348
81       0    40   81   81  53346867 -6230852
82      10    20   82   82  53341805 -6305085
83      12     8   83   83  53356769 -6268140
84       0    40   84   84  53343897 -6297060
85       0    38   85   85  53347477 -6285250
86       0    30   86   86  53348800 -6281637
87      13    27   87   87  53342113 -6310015
88       0    40   88   88  53346985 -6297804
89      31     9   89   89  53344153 -6233451
90      40     0   90   90  53341515 -6256853
91      22     7   91   91  53341833 -6231291
92       3    37   92   92  53339983 -6295594
93      11    29   93   93  53347802 -6292432
94       0    22   94   94  53341645 -6297190
95      28     0   95   95  53340962 -6262287
96       5    25   96   96  53334123 -6265436
97      16     7   97   97  53339629 -6243778
98       0    16   98   98  53355473 -6264423
99      10    26   99   99  53334030 -6260714
100      9    11  100  100  53340803 -6267732

                                  name  number               timestamp
0                        FENIAN STREET      63 2016-03-07 13:32:43.746
1                            CITY QUAY      99 2016-03-07 13:32:43.779
2              FITZWILLIAM SQUARE EAST      89 2016-03-07 13:32:44.085
3                      BROOKFIELD ROAD      84 2016-03-07 13:32:43.712
4                           EMMET ROAD      83 2016-03-07 13:32:44.097
5                          ROTHE ABBEY      85 2016-03-07 13:32:44.080
6                    KING STREET NORTH     101 2016-03-07 13:32:43.765
7                         GREEK STREET       4 2016-03-07 13:32:43.813
8                          WESTERN WAY     102 2016-03-07 13:32:43.763
9                     CHARLEMONT PLACE       5 2016-03-07 13:32:43.804
10                     PARKGATE STREET      86 2016-03-07 13:32:44.066
11                         HIGH STREET       7 2016-03-07 13:32:43.815
12              HEUSTON BRIDGE (SOUTH)     100 2016-03-07 13:32:44.068
13                  PORTOBELLO HARBOUR      34 2016-03-07 13:32:43.880
14                  ECCLES STREET EAST      79 2016-03-07 13:32:43.910
15                 MERRION SQUARE EAST      25 2016-03-07 13:32:43.939
16                          SMITHFIELD      35 2016-03-07 13:32:43.986
17                     PORTOBELLO ROAD      43 2016-03-07 13:32:43.732
18                   CUSTOM HOUSE QUAY       8 2016-03-07 13:32:43.881
19                 MERRION SQUARE WEST      26 2016-03-07 13:32:43.975
20                     HARDWICKE PLACE      61 2016-03-07 13:32:43.806
21            ST. STEPHEN'S GREEN EAST      36 2016-03-07 13:32:43.955
22                   MOLESWORTH STREET      27 2016-03-07 13:32:43.895
23               UPPER SHERRARD STREET      44 2016-03-07 13:32:44.083
24                MOUNTJOY SQUARE WEST      28 2016-03-07 13:32:44.047
25                         LIME STREET      62 2016-03-07 13:32:43.753
26                    EXCHEQUER STREET       9 2016-03-07 13:32:43.780
27                   ORMOND QUAY UPPER      29 2016-03-07 13:32:44.090
28                    NEW CENTRAL BANK      66 2016-03-07 13:32:43.850
29                         DAME STREET      10 2016-03-07 13:32:43.999
..                                 ...     ...                     ...
71                   CONVENTION CENTRE      65 2016-03-07 13:32:43.976
72   PRINCES STREET / O'CONNELL STREET      33 2016-03-07 13:32:44.013
73                   WOLFE TONE STREET      77 2016-03-07 13:32:43.809
74                  OLIVER BOND STREET      74 2016-03-07 13:32:43.706
75                       BARROW STREET      70 2016-03-07 13:32:44.039
76                       HERBERT PLACE      19 2016-03-07 13:32:43.759
77                    GRAND CANAL DOCK      69 2016-03-07 13:32:43.935
78                DENMARK STREET GREAT      59 2016-03-07 13:32:43.953
79                      FRANCIS STREET      73 2016-03-07 13:32:43.811
80                 NORTH CIRCULAR ROAD      60 2016-03-07 13:32:43.835
81                           THE POINT      67 2016-03-07 13:32:43.750
82                     KILMAINHAM LANE      96 2016-03-07 13:32:43.898
83                  BLESSINGTON STREET       2 2016-03-07 13:32:43.968
84                      ROYAL HOSPITAL      95 2016-03-07 13:32:43.864
85             COLLINS BARRACKS MUSEUM      87 2016-03-07 13:32:43.709
86                     BLACKHALL PLACE      88 2016-03-07 13:32:44.105
87                     KILMAINHAM GAOL      97 2016-03-07 13:32:43.754
88          HEUSTON STATION (CAR PARK)      94 2016-03-07 13:32:43.954
89                       BENSON STREET      90 2016-03-07 13:32:43.745
90              FREDERICK STREET SOUTH      98 2016-03-07 13:32:43.737
91                     SOUTH DOCK ROAD      91 2016-03-07 13:32:43.748
92        ST. JAMES HOSPITAL (CENTRAL)      81 2016-03-07 13:32:43.699
93              HEUSTON BRIDGE (NORTH)      92 2016-03-07 13:32:44.099
94                         MOUNT BROWN      82 2016-03-07 13:32:43.857
95                      CHATHAM STREET       1 2016-03-07 13:32:43.740
96                     GRANTHAM STREET      18 2016-03-07 13:32:43.725
97                      GRATTAN STREET      57 2016-03-07 13:32:44.020
98                    HARDWICKE STREET      15 2016-03-07 13:32:43.982
99                        HATCH STREET      55 2016-03-07 13:32:43.800
100                        GOLDEN LANE      17 2016-03-07 13:32:43.772

[101 rows x 9 columns]
101

In [26]:
#Create the Data Frame
pd.concat([bike_frame])

,bikes,free,id,idx,lat,lng,name,number,timestamp
0,33,0,0,0,53341428,-6246720,FENIAN STREET,63,2016-03-07 13:32:43.746
1,15,15,1,1,53346637,-6246154,CITY QUAY,99,2016-03-07 13:32:43.779
2,23,16,2,2,53335211,-6250900,FITZWILLIAM SQUARE EAST,89,2016-03-07 13:32:44.085
3,1,29,3,3,53339005,-6300217,BROOKFIELD ROAD,84,2016-03-07 13:32:43.712
4,10,30,4,4,53340714,-6308191,EMMET ROAD,83,2016-03-07 13:32:44.097
5,1,34,5,5,53338776,-6303950,ROTHE ABBEY,85,2016-03-07 13:32:44.080
6,2,28,6,6,53350291,-6273507,KING STREET NORTH,101,2016-03-07 13:32:43.765
7,12,8,7,7,53346874,-6272976,GREEK STREET,4,2016-03-07 13:32:43.813
8,0,40,8,8,53354929,-6269425,WESTERN WAY,102,2016-03-07 13:32:43.763
9,10,30,9,9,53330662,-6260177,CHARLEMONT PLACE,5,2016-03-07 13:32:43.804
10,1,37,10,10,53347972,-6291804,PARKGATE STREET,86,2016-03-07 13:32:44.066
11,4,25,11,11,53343565,-6275071,HIGH STREET,7,2016-03-07 13:32:43.815
12,12,13,12,12,53347106,-6292041,HEUSTON BRIDGE (SOUTH),100,2016-03-07 13:32:44.068
13,4,26,13,13,53330362,-6265163,PORTOBELLO HARBOUR,34,2016-03-07 13:32:43.880
14,0,27,14,14,53358115,-6265601,ECCLES STREET EAST,79,2016-03-07 13:32:43.910
15,30,0,15,15,53339434,-6246548,MERRION SQUARE EAST,25,2016-03-07 13:32:43.939
16,6,24,16,16,53347692,-6278214,SMITHFIELD,35,2016-03-07 13:32:43.986
17,3,27,17,17,53330091,-6268044,PORTOBELLO ROAD,43,2016-03-07 13:32:43.732
18,20,9,18,18,53347884,-6248048,CUSTOM HOUSE QUAY,8,2016-03-07 13:32:43.881
19,18,2,19,19,53339764,-6251988,MERRION SQUARE WEST,26,2016-03-07 13:32:43.975
20,1,24,20,20,53357043,-6263232,HARDWICKE PLACE,61,2016-03-07 13:32:43.806
21,38,2,21,21,53337824,-6256035,ST. STEPHEN'S GREEN EAST,36,2016-03-07 13:32:43.955
22,14,6,22,22,53341288,-6258117,MOLESWORTH STREET,27,2016-03-07 13:32:43.895
23,0,30,23,23,53358437,-6260641,UPPER SHERRARD STREET,44,2016-03-07 13:32:44.083
24,0,30,24,24,53356299,-6258586,MOUNTJOY SQUARE WEST,28,2016-03-07 13:32:44.047
25,20,20,25,25,53346026,-6243576,LIME STREET,62,2016-03-07 13:32:43.753
26,23,1,26,26,53343034,-6263578,EXCHEQUER STREET,9,2016-03-07 13:32:43.780
27,9,20,27,27,53346057,-6268001,ORMOND QUAY UPPER,29,2016-03-07 13:32:44.090
28,0,40,28,28,53347122,-6234749,NEW CENTRAL BANK,66,2016-03-07 13:32:43.850
29,15,1,29,29,53344007,-6266802,DAME STREET,10,2016-03-07 13:32:43.999
...,...,...,...,...,...,...,...,...,...
71,2,38,71,71,53347440,-6238523,CONVENTION CENTRE,65,2016-03-07 13:32:43.976
72,17,6,72,72,53349013,-6260311,PRINCES STREET / O'CONNELL STREET,33,2016-03-07 13:32:44.013
73,10,19,73,73,53348875,-6267459,WOLFE TONE STREET,77,2016-03-07 13:32:43.809
74,0,30,74,74,53343893,-6280531,OLIVER BOND STREET,74,2016-03-07 13:32:43.706
75,38,2,75,75,53341655,-6236198,BARROW STREET,70,2016-03-07 13:32:44.039
76,24,5,76,76,53334432,-6245575,HERBERT PLACE,19,2016-03-07 13:32:43.759
77,30,9,77,77,53342638,-6238695,GRAND CANAL DOCK,69,2016-03-07 13:32:43.935
78,0,20,78,78,53355610,-6261397,DENMARK STREET GREAT,59,2016-03-07 13:32:43.953
79,0,30,79,79,53342081,-6275233,FRANCIS STREET,73,2016-03-07 13:32:43.811
80,2,28,80,80,53359624,-6260348,NORTH CIRCULAR ROAD,60,2016-03-07 13:32:43.835
81,0,40,81,81,53346867,-6230852,THE POINT,67,2016-03-07 13:32:43.750
82,10,20,82,82,53341805,-6305085,KILMAINHAM LANE,96,2016-03-07 13:32:43.898
83,12,8,83,83,53356769,-6268140,BLESSINGTON STREET,2,2016-03-07 13:32:43.968
84,0,40,84,84,53343897,-6297060,ROYAL HOSPITAL,95,2016-03-07 13:32:43.864
85,0,38,85,85,53347477,-6285250,COLLINS BARRACKS MUSEUM,87,2016-03-07 13:32:43.709
86,0,30,86,86,53348800,-6281637,BLACKHALL PLACE,88,2016-03-07 13:32:44.105
87,13,27,87,87,53342113,-6310015,KILMAINHAM GAOL,97,2016-03-07 13:32:43.754
88,0,40,88,88,53346985,-6297804,HEUSTON STATION (CAR PARK),94,2016-03-07 13:32:43.954
89,31,9,89,89,53344153,-6233451,BENSON STREET,90,2016-03-07 13:32:43.745
90,40,0,90,90,53341515,-6256853,FREDERICK STREET SOUTH,98,2016-03-07 13:32:43.737
91,22,7,91,91,53341833,-6231291,SOUTH DOCK ROAD,91,2016-03-07 13:32:43.748
92,3,37,92,92,53339983,-6295594,ST. JAMES HOSPITAL (CENTRAL),81,2016-03-07 13:32:43.699
93,11,29,93,93,53347802,-6292432,HEUSTON BRIDGE (NORTH),92,2016-03-07 13:32:44.099
94,0,22,94,94,53341645,-6297190,MOUNT BROWN,82,2016-03-07 13:32:43.857
95,28,0,95,95,53340962,-6262287,CHATHAM STREET,1,2016-03-07 13:32:43.740
96,5,25,96,96,53334123,-6265436,GRANTHAM STREET,18,2016-03-07 13:32:43.725
97,16,7,97,97,53339629,-6243778,GRATTAN STREET,57,2016-03-07 13:32:44.020
98,0,16,98,98,53355473,-6264423,HARDWICKE STREET,15,2016-03-07 13:32:43.982
99,10,26,99,99,53334030,-6260714,HATCH STREET,55,2016-03-07 13:32:43.800
100,9,11,100,100,53340803,-6267732,GOLDEN LANE,17,2016-03-07 13:32:43.772

In [27]:
import csv

with open('output.csv', 'a') as file:
    file.write(json_data)
    
with open('output.json', 'a') as jfile:
    jfile.write(json_data)

In [28]:
#TEST1  -check that number of rows in dataframe = 101 (1 row per station)

def test_all_records():
    test1 = len(bike_frame.index)
    if test1 == 101:
        return True
    else:
        return False

In [29]:
#Get the count for each data type
bike_frame.count()

bikes        101
free         101
id           101
idx          101
lat          101
lng          101
name         101
number       101
timestamp    101
dtype: int64

In [30]:
#TEST2 - check that the number of bike if correct
#need to modify to get only sum for 'bikes' data

#CHANGE CODE TO ADD ALL "bikes" AND ALL "free" to get 3153 total 

def test_total_bikes():
    test = bike_frame.sum(axis=0)   #column sum
    test = test2[0]                 #--> 3153
    print("..."+ test)
    if test > 3153:
        return ("Too many Bikes")
    elif test == 3153:
        return ("Correct")
    else test < 3153:
        return ("Not enough Bikes")

SyntaxError: invalid syntax (<ipython-input-30-f37e43c56fac>, line 14)

In [ ]:
bike_frame.sum()

In [31]:
sum = df("bikes") + df("free")
print(sum)

NameError: name 'df' is not defined